import type { Metadata } from 'next'
import './globals.css'
import { AlertProvider } from '@/components/alert'
import { UserProvider } from '@/contexts/userContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <AlertProvider>
          <UserProvider>{children}</UserProvider>
        </AlertProvider>
      </body>
    </html>
  )
}
